on: [push]
permissions: {}
jobs:
  build-chain:
    permissions: read-all|write-all
    runs-on: ubuntu-latest
    steps:
      - name: "echo inside this repo"
        run: |
          echo "echo inside TestUpperStream"
      - name: Invoke workflow in another repo
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          repo: wuisky/try-dispatched
          ref: master
          # token: "${{ secrets.GITHUB_TOKEN }}"
          token:  ${{ secrets.github_token }}
          workflow: workflow.yml
          inputs: '{"push_to_registries": "true"}'
