on: [push]
permissions: {}
jobs:
  build-chain:
    env:
      GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
      # GITHUB_TOKEN: ${{ secrets.STANDARD_RIGHTS }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Echo inside this repo
        run: |
          echo "echo inside TestUpperStream"
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.STANDARD_RIGHTS }}
          repository: wuisky/try-dispatched
          retain_days: 0
          keep_minimum_runs: 0
      - name: Invoke workflow in another repo
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          repo: wuisky/try-dispatched
          ref: master
          token: ${{ secrets.STANDARD_RIGHTS }}
          workflow: workflow.yml
          inputs: "{ 'upstream_branch': ${{ github.head_ref }} }"
      - name: Wait dispatch
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-build-common
        with:
          repo: try-dispatched
          ref: master
          # token: ${{ secrets.STANDARD_RIGHTS }}
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build-chain
          intervalSeconds: 5
      - name: Build failure
        if: steps.wait-for-build-common.outputs.conclusion != 'success'
        uses: actions/github-script@v6.4.0
        with:
          script: |
            core.setFailed('Build failed!')
